In [1]:
import pandas as pd
from arcgis.features import GeoAccessor, GeoSeriesAccessor

## Dataset Feature Identifications

Here is a list of all thew Feature ID which can be used for performing the data queries from the Feature Layer (Hosted) within the **COVID-19 Hub for Zimbabwe**. 

*Infections Time Series* - `42ec33c9361d49b585a23d780207726d`

*Vaccination Time Series* - `0bad4380917a48da8f4f12028709c443`. 
The Vaccination Times Series contains 3 layers within the Feature Layer. For the Time Series Data query the layer with Index [2]

*Provincial Cases* - `122efe4c5ab54ff9a9e75cc1908d48f4`

*Provincial Time Series* - `20703dd3a24f45f08ea37034285d3492`. 
This one is a new introduction to the daily reporting system for COVID-19 within the Hub.

In [2]:
from arcgis import GIS
gis = GIS()
item = gis.content.get("42ec33c9361d49b585a23d780207726d") # Contains the Feature ID for the Infections Time-Series layer
flayer = item.layers[0]

# create a Spatially Enabled DataFrame object
sdf = pd.DataFrame.spatial.from_layer(flayer)
sdf.head()

,FID,Date,Total_Cumu,New_Cases,PCR,Recovered,Deaths,Daily_Posi,Country,RDT,...,conditio_1,conditio_2,asymptomat,total_vacc,total_vacc_2,hotspot_cities,lockdown_update,keyNotes,newHosp,SHAPE
0,1,2021-04-22,38018.0,38.0,1945.0,8,0,2.00,,0.0,...,8.0,13.0,2.0,308071.0,NaN,"Kariba, Chidamoyo, Karoi, Chinhoyi, Chegutu, B...",L4,9 cases in Manicaland are from the same school...,NaN,"{""x"": 3321810.106932258, ""y"": -2215664.6305056..."
1,2,2021-04-23,38045.0,27.0,1332.0,21,1,2.00,,0.0,...,10.0,3.0,1.0,319732.0,NaN,None,None,The 18 cases from Mat North are all from a min...,NaN,"{""x"": 3321812.4001137684, ""y"": -2215661.819628..."
2,3,2021-04-24,38064.0,19.0,1583.0,7,0,1.20,,0.0,...,1.0,0.0,12.0,324488.0,NaN,None,None,7 of the 8 cases reported by Mat North are fro...,NaN,"{""x"": 3321793.0193904215, ""y"": -2215663.484895..."
3,4,2021-04-25,38086.0,22.0,1279.0,22,1,1.70,,0.0,...,0.0,0.0,12.0,336600.0,NaN,None,None,6 of the 7 cases reported by Mat North are fro...,NaN,"{""x"": 3321812.0216275, ""y"": -2215663.874639421..."
4,5,2021-04-26,38102.0,16.0,1495.0,26,3,1.07,,0.0,...,7.0,3.0,13.0,353834.0,NaN,None,None,6 of the 7 cases reported by Mat North are fro...,NaN,"{""x"": 3321805.6764165247, ""y"": -2215666.437498..."

## Query The Layer to Return intended Display

Lets return the records for the latest data update for out data

In [3]:
''' retrieve using the largest number of Cumulative tests
Would really love to use the date but its a bit buggy
'''
largest_cum_value = sdf["Total_Cumu"].max()

# Let's see if it works
print(largest_cum_value)

117954.0

In [4]:
latest_records = sdf.query("Total_Cumu == @largest_cum_value")

In [5]:
# Retrieve the Latest Records from the data
latest_records[['Date', 'Total_Cumu', 'New_Cases', 'PCR', 'Recovered', 'Deaths', 'Daily_Posi', 'conditio_1', 'conditio_2', 'asymptomat', 'total_vacc', 'total_vacc_2', 'hotspot_cities', 'lockdown_update', 'keyNotes', 'newHosp']].head()

,Date,Total_Cumu,New_Cases,PCR,Recovered,Deaths,Daily_Posi,conditio_1,conditio_2,asymptomat,total_vacc,total_vacc_2,hotspot_cities,lockdown_update,keyNotes,newHosp
512,2021-08-11 21:12:00,117954.0,696.0,6812.0,2003,41,10.2,79.0,34.0,90.0,1933220.0,1084392.0,"Hurungwe, Kariba, Makonde, Bindura, Mazowe, Ma...",L4,Cases in the area previously designated as Hot...,31.0

## Export the Data as CSV File

In [6]:
sdf.to_csv(r"C:\Users\<username>\Desktop\GitHub Repositories\Zimbabwe-COVID-19-Data\time_series_data\daily_cumulative_records.csv")